"""
Django settings for TabebAI project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_&(6m7f55(qkeoqrpxq971h5)mm(fi7c&3l9wjtonfvh)zrqj@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    'corsheaders',
    #اضافاات تسجيل الدخول 
    'django.contrib.sites',
    #1 اعدادات dj-rest-auth
    'dj_rest_auth',
    'rest_framework',
    'rest_framework.authtoken',
    #اعدادات django-allauth
    'allauth',
    'allauth.account',
    'dj_rest_auth.registration',
    'allauth.socialaccount',
    #app
    'users',
    'Doctor',
    'Patients',    
    'QR',
    'RAG',
    'AvatarAI',
]

PASSWORD_RESET_CONFIRM_URL = "TabebAI/password/reset/confirm/{uid}/{token}/"
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
REST_AUTH_TOKEN_MODEL=None
SITE_ID = 1
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_AUTHENTICATION_METHOD = "username"
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_PASSWORD_RESET_CONFIRM_URL = 'reset-password/{uid}/{token}/'

FRONTEND_URL = "http://localhost:5173"
  

DJANGO_REST_AUTH = {
    "PASSWORD_RESET_CONFIRM_URL": "password/reset/confirm/{uid}/{token}/",  
    "USE_JWT": False,
    }
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'    
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'almtwali1222@gmail.com'  
EMAIL_HOST_PASSWORD = 'ssvs auom hzaf jbou'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #الاضافات
    'allauth.account.middleware.AccountMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',    
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
  "DEFAULT_AUTHENTICATION_CLASSES": [
      'rest_framework_simplejwt.authentication.JWTAuthentication',
      "rest_framework.authentication.TokenAuthentication",
    "rest_framework.authentication.SessionAuthentication",  
    
  ],
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


ROOT_URLCONF = 'TabebAI.urls'

PASSWORD_RESET_TIMEOUT = 60 * 60 * 24  

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TabebAI.wsgi.application'

ALLOWED_HOSTS = ['*']

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':'Junior',
        'USER':'postgres',
        'PASSWORD':'2002',
        'HOST':'localhost',
        'PORT':'5432',
    
        }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

