# Generated by Django 5.2.1 on 2025-06-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsdb',
            name='specialty',
            field=models.CharField(default='طبيب عام', max_length=50),
        ),
    ]
