# Generated by Django 5.2.1 on 2025-06-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_alter_doctorsdb_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsdb',
            name='user',
        ),
    ]
