# Generated by Django 5.2.7 on 2025-10-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_doctorsdb_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsdb',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=6),
        ),
        migrations.AlterField(
            model_name='doctorsdb',
            name='license_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
