# Generated by Django 5.2.1 on 2025-06-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_remove_doctorsdb_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsdb',
            name='license_number',
            field=models.CharField(unique=True),
        ),
    ]
