# Generated by Django 5.2.1 on 2025-06-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_alter_doctorsdb_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsdb',
            name='is_admin',
        ),
    ]
