# Generated by Django 5.2.1 on 2025-06-10 13:34

import Patients.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('fathers_name', models.CharField(max_length=20)),
                ('mothers_name', models.CharField(max_length=20)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], help_text='اختر فصيلة الدم', max_length=3, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('weight', models.CharField(max_length=3)),
                ('height', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'انثى')], max_length=8)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=Patients.models.patient_photo_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
