# Generated by Django 5.2.7 on 2025-11-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdb',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
