# Generated by Django 5.2.7 on 2025-11-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0003_alter_patientdb_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdb',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
