# Generated by Django 5.2.1 on 2025-06-13 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0002_doctorsdb_user'),
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recipes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Doctor.doctorsdb')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Patients.patientdb')),
            ],
        ),
    ]
