# Generated by Django 5.2.1 on 2025-06-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0003_alter_visit_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='treatment_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
