# Generated by Django 5.2.7 on 2025-11-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0004_visit_expires_at_visit_is_permanent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='Test_Request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='Type_of_Test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
