# Generated by Django 5.2.7 on 2025-11-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0005_visit_test_request_visit_type_of_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='treatment_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
