# Generated by Django 5.2.7 on 2025-11-11 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptech', '0001_initial'),
        ('Patients', '0001_initial'),
        ('QR', '0006_alter_visit_treatment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('laptech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Laptech.labtechdb')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Patients.patientdb')),
            ],
        ),
    ]
