# Generated by Django 5.2.7 on 2025-11-12 04:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0007_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='test_results/'),
        ),
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test_results/imgs/'),
        ),
        migrations.AddField(
            model_name='session',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
