# Generated by Django 5.2.7 on 2025-11-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0008_session_file_session_image_session_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='AnalysisExplanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
