# Generated by Django 5.2.7 on 2025-11-12 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0009_session_analysisexplanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QR.visit'),
        ),
    ]
