# Generated by Django 5.2.7 on 2025-11-12 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_alter_doctorsdb_gender_and_more'),
        ('QR', '0010_session_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Doctor.doctorsdb'),
        ),
    ]
