# Generated by Django 5.2.7 on 2025-11-12 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_alter_doctorsdb_gender_and_more'),
        ('Patients', '0001_initial'),
        ('QR', '0011_session_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='Doctor.doctorsdb'),
        ),
        migrations.AlterField(
            model_name='session',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='Patients.patientdb'),
        ),
        migrations.AlterField(
            model_name='session',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='QR.visit'),
        ),
    ]
