# Generated by Django 5.2.7 on 2025-11-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
