# Generated by Django 5.2.7 on 2025-11-22 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0014_notification_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits_for_this_session', to='QR.session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_for_this_visit', to='QR.visit'),
        ),
    ]
